### ISSUE TITLE
conf-scrap-conf sequence fails with `AddressAlreadyInUse` error

### ISSUE THREAD

**Issue by alessandrothea** [DUNE-DAQ/nwqueueadapters#10]
Reproducible with minidaqapp (I know, not the most essential example, but...) & nanorc

```
nanorc/nanorc.py -l WARNING nanorc/examples/mdapp_fake boot init conf scrap conf
```

results in 
```
[10:27:58] ERROR    ERROR: Failed to execute 'conf' on ruemu_df, trgemu applications                                           core.py:79
           ERROR    ruemu_df: {'appname': 'ruemu_df', 'data': {'ans-host': '128.141.174.134', 'ans-port': '13334', 'cmdid':    core.py:81
                    'conf'}, 'result': 'Address already in use', 'success': False}
           ERROR    trgemu: {'appname': 'trgemu', 'data': {'ans-host': '128.141.174.134', 'ans-port': '13333', 'cmdid':        core.py:81
                    'conf'}, 'result': 'Address already in use', 'success': False}
```

**Comment by philiprodrigues** [comment]
Good catch. There was a missing call to destruct an object in `scrap`, along with some missing `virtual`s on destructors. Fixed by the combination of:

https://github.com/DUNE-DAQ/nwqueueadapters/commit/d4a122d82c8eed94b3be3252d53628cd7bb5d1bd
https://github.com/DUNE-DAQ/nwqueueadapters/commit/4aa8ea1a9d563c2a0348b7126cae059c7cbc840a
https://github.com/DUNE-DAQ/ipm/pull/41
